export const siteConfig = {
  name: "Super Koffee",
  tagline: "Cerita Hati Melalui Kopi",
  description:
    "Super Koffee — coffee shop multi-cabang di Surabaya. Nikmati Kopi Susu Maksud Hati dan menu andalan lainnya di Manukan, Wiyung, stasiun, dan cabang lainnya.",
  phone: "+62 812-3456-7890",
  whatsapp: "6281234567890",
  email: "hello@superkoffee.id",
  address: "Jl. Raya Manukan Kulon No.22, Surabaya",
  social: {
    instagram: "https://www.instagram.com/superkoffee/",
    tiktok: "https://www.tiktok.com/@superkoffee",
    facebook: "https://facebook.com/superkoffee",
  },
};

export const categories = [
  { id: 1, name: "Kopi", slug: "kopi" },
  { id: 2, name: "Non-Kopi", slug: "non-kopi" },
  { id: 3, name: "Snack & Dessert", slug: "snack" },
];

export const menuItems = [
  {
    id: 1,
    name: "Kopi Susu Maksud Hati",
    slug: "kopi-susu-maksud-hati",
    description: "Signature Super Koffee — espresso blend dengan susu segar, rasa seimbang dan creamy",
    price: 18000,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=750&fit=crop",
    badge: "best_seller" as const,
    categoryId: 1,
  },
  {
    id: 2,
    name: "Kopi Susu Gula Aren",
    slug: "kopi-susu-gula-aren",
    description: "Kopi susu dengan manis alami gula aren lokal",
    price: 20000,
    image: "/kopsuaren.png",
    badge: "best_seller" as const,
    categoryId: 1,
  },
  {
    id: 3,
    name: "Americano",
    slug: "americano",
    description: "Espresso shot dengan air panas, rasa bold dan clean",
    price: 15000,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=750&fit=crop",
    badge: null,
    categoryId: 1,
  },
  {
    id: 4,
    name: "Cappuccino",
    slug: "cappuccino",
    description: "Espresso, steamed milk, dan foam yang lembut",
    price: 22000,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&h=750&fit=crop",
    badge: null,
    categoryId: 1,
  },
  {
    id: 5,
    name: "Matcha Latte",
    slug: "matcha-latte",
    description: "Matcha premium dengan susu pilihan",
    price: 25000,
    image: "/Matcha.png",
    badge: "new" as const,
    categoryId: 2,
  },
  {
    id: 6,
    name: "Chocolate",
    slug: "chocolate",
    description: "Cokelat hangat / dingin yang creamy",
    price: 22000,
    image: "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&h=750&fit=crop",
    badge: null,
    categoryId: 2,
  },
  {
    id: 7,
    name: "Donut",
    slug: "donut",
    description: "Donut lembut, cocok dipasangkan dengan Kopi Susu Maksud Hati",
    price: 12000,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600&h=750&fit=crop",
    badge: "promo" as const,
    categoryId: 3,
  },
  {
    id: 8,
    name: "Ice Cream",
    slug: "ice-cream",
    description: "Es krim pilihan untuk dampingan kopi",
    price: 15000,
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=600&h=750&fit=crop",
    badge: null,
    categoryId: 3,
  },
];

export const features = [
  {
    title: "Kopi Susu Signature",
    description: "Kopi Susu Maksud Hati jadi andalan pelanggan di seluruh cabang Surabaya.",
    icon: "Coffee",
  },
  {
    title: "Multi Cabang",
    description: "Hadir di Manukan, Wiyung, stasiun kereta, dan lokasi strategis lainnya.",
    icon: "MapPin",
  },
  {
    title: "Order Online",
    description: "Tersedia di GrabFood & ShopeeFood — praktis dari rumah atau kantor.",
    icon: "Smartphone",
  },
  {
    title: "Harga Bersahabat",
    description: "Rasa premium dengan harga yang affordable untuk semua kalangan.",
    icon: "Heart",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rina S.",
    rating: 5,
    text: "Kopi Susu Maksud Hati-nya juara! Rutin mampir di cabang Manukan sebelum kerja.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
  {
    id: 2,
    name: "Andi P.",
    rating: 5,
    text: "Cabang di stasiun Gubeng sangat membantu. Ngopi dulu sebelum naik kereta, pas banget.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    id: 3,
    name: "Sarah L.",
    rating: 4,
    text: "Harga oke, rasa konsisten di semua cabang. Favorite banget sama yang gula aren.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
  },
];

export const branches = [
  {
    id: 1,
    name: "Super Koffee Manukan",
    slug: "manukan",
    address: "Jl. Raya Manukan Kulon No.22, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7890",
    whatsapp: "6281234567890",
    hours: "Weekday 11:00–22:00 · Weekend 11:00–23:00",
    isOpen: true,
  },
  {
    id: 2,
    name: "Super Koffee Wiyung",
    slug: "wiyung",
    address: "Jl. Raya Wiyung No.401, Wiyung, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7891",
    whatsapp: "6281234567891",
    hours: "Setiap hari 10:00–23:00",
    isOpen: true,
  },
  {
    id: 3,
    name: "Super Koffee Perak",
    slug: "perak",
    address: "Jl. Rajawali 102, Perak, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7892",
    whatsapp: "6281234567892",
    hours: "Weekday 09:00–22:00 · Weekend 09:00–23:00",
    isOpen: true,
  },
  {
    id: 4,
    name: "Super Koffee Stasiun Pasar Turi",
    slug: "pasar-turi",
    address: "Lobby Keberangkatan Ekonomi, Stasiun Pasar Turi, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7893",
    whatsapp: "6281234567893",
    hours: "Setiap hari 06:00–22:00",
    isOpen: true,
  },
  {
    id: 5,
    name: "Super Koffee Stasiun Gubeng Baru",
    slug: "gubeng",
    address: "Sebelah Pintu Kedatangan, Stasiun Gubeng Baru, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7894",
    whatsapp: "6281234567894",
    hours: "Setiap hari 06:00–22:00",
    isOpen: true,
  },
  {
    id: 6,
    name: "Super Koffee Jemursari",
    slug: "jemursari",
    address: "Jl. Raya Jemursari 157-159A, Surabaya",
    city: "Surabaya",
    phone: "+62 812-3456-7895",
    whatsapp: "6281234567895",
    hours: "Segera kembali buka",
    isOpen: false,
  },
];

export const articles = [
  {
    id: 1,
    title: "Kenalan dengan Kopi Susu Maksud Hati",
    slug: "kopi-susu-maksud-hati",
    excerpt: "Signature Super Koffee yang jadi favorit pelanggan di seluruh cabang Surabaya. Apa yang bikin istimewa?",
    thumbnail: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&h=400&fit=crop",
    category: "Menu",
    publishedAt: "2026-08-15",
    readTime: "3 menit",
  },
  {
    id: 2,
    title: "Ngopi di Stasiun? Bisa di Super Koffee",
    slug: "ngopi-di-stasiun",
    excerpt: "Cabang di Stasiun Pasar Turi dan Gubeng Baru siap nemenin perjalananmu dengan kopi hangat.",
    thumbnail: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&h=400&fit=crop",
    category: "Cabang",
    publishedAt: "2026-07-20",
    readTime: "4 menit",
  },
  {
    id: 3,
    title: "Cerita di Balik Nama Super Koffee",
    slug: "cerita-super-koffee",
    excerpt: "Dari satu outlet hingga multi-cabang di Surabaya. Bagaimana perjalanan brand ini dimulai?",
    thumbnail: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
    category: "Cerita",
    publishedAt: "2026-06-10",
    readTime: "5 menit",
  },
];

export const galleryImages = [
  {
    id: 1,
    title: "Kopi Susu Maksud Hati",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=600&fit=crop",
    category: "produk",
    alt: "Kopi Susu Maksud Hati Super Koffee",
  },
  {
    id: 2,
    title: "Interior Cafe",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop",
    category: "outlet",
    alt: "Interior Super Koffee",
  },
  {
    id: 3,
    title: "Barista di Kerja",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop",
    category: "event",
    alt: "Barista Super Koffee sedang menyiapkan kopi",
  },
  {
    id: 4,
    title: "Donut & Kopi",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&h=600&fit=crop",
    category: "produk",
    alt: "Donut dampingan kopi Super Koffee",
  },
  {
    id: 5,
    title: "Suasana Outlet",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop",
    category: "outlet",
    alt: "Suasana outlet Super Koffee",
  },
  {
    id: 6,
    title: "Latte Art",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&h=600&fit=crop",
    category: "produk",
    alt: "Latte art Super Koffee",
  },
];
